# version: '3.8'

services:
  backend:
    build:
      context: ./base  
      dockerfile: ./Dockerfile
    volumes:
      - ./base:/app  
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 base.wsgi:application  

    # depends_on:
    #   - db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"


# db:
#   image: postgres:13
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   environment:
#     POSTGRES_DB: mydb
#     POSTGRES_USER: myuser
#     POSTGRES_PASSWORD: mypassword


# volumes:
#   postgres_data:
