services:
  backend:
    type: docker
    env: docker
    dockerfilePath: ./base/Dockerfile
    autoDeploy: true
    buildCommand: docker build -t chat_app_pro-backend ./base
    startCommand: gunicorn base.wsgi:application --bind 0.0.0.0:8000
    plan: free
    region: oregon
    
  frontend:
    type: docker
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    buildCommand: docker build -t chat_app_pro-frontend ./frontend
    startCommand: serve -s build -l 3000
    plan: free
    region: oregon
