services:
  - name: blairn-chat-backend
    type: docker
    env: docker
    dockerfilePath: ./base/Dockerfile
    autoDeploy: true
    startCommand: gunicorn base.base.wsgi:application --bind 0.0.0.0:${PORT:-8000}
    plan: free
    region: oregon
    
  - name: blairn-chat-frontend
    type: docker
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    startCommand: serve -s build -l 3000  # Ensure you have a way to serve your frontend
    plan: free
    region: oregon
